# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Latest::PostDeleteForm`.
# Please instead update this file by running `bin/tapioca dsl Latest::PostDeleteForm`.

class Latest::PostDeleteForm
  sig { returns(T.nilable(::String)) }
  def target_post_id; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def target_post_id=(value); end
end
