// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actors.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const getActorByID = `-- name: GetActorByID :one
SELECT id, user_id, profile_id, created_at, updated_at
FROM actors
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetActorByID(ctx context.Context, id uuid.UUID) (Actor, error) {
	row := q.db.QueryRowContext(ctx, getActorByID, id)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActorByUserID = `-- name: GetActorByUserID :one
SELECT id, user_id, profile_id, created_at, updated_at
FROM actors
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetActorByUserID(ctx context.Context, userID uuid.UUID) (Actor, error) {
	row := q.db.QueryRowContext(ctx, getActorByUserID, userID)
	var i Actor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
