// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type Actor struct {
	ID        uuid.UUID `db:"id"`
	UserID    uuid.UUID `db:"user_id"`
	ProfileID uuid.UUID `db:"profile_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type ArInternalMetadatum struct {
	Key       string         `db:"key"`
	Value     sql.NullString `db:"value"`
	CreatedAt time.Time      `db:"created_at"`
	UpdatedAt time.Time      `db:"updated_at"`
}

type EmailConfirmation struct {
	ID          uuid.UUID    `db:"id"`
	Email       string       `db:"email"`
	Event       string       `db:"event"`
	Code        string       `db:"code"`
	SucceededAt sql.NullTime `db:"succeeded_at"`
	CreatedAt   time.Time    `db:"created_at"`
	UpdatedAt   time.Time    `db:"updated_at"`
}

type Follow struct {
	ID              uuid.UUID `db:"id"`
	SourceProfileID uuid.UUID `db:"source_profile_id"`
	TargetProfileID uuid.UUID `db:"target_profile_id"`
	FollowedAt      time.Time `db:"followed_at"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
}

type GoodJob struct {
	ID               uuid.UUID             `db:"id"`
	QueueName        sql.NullString        `db:"queue_name"`
	Priority         sql.NullInt32         `db:"priority"`
	SerializedParams pqtype.NullRawMessage `db:"serialized_params"`
	ScheduledAt      sql.NullTime          `db:"scheduled_at"`
	PerformedAt      sql.NullTime          `db:"performed_at"`
	FinishedAt       sql.NullTime          `db:"finished_at"`
	Error            sql.NullString        `db:"error"`
	CreatedAt        time.Time             `db:"created_at"`
	UpdatedAt        time.Time             `db:"updated_at"`
	ActiveJobID      uuid.NullUUID         `db:"active_job_id"`
	ConcurrencyKey   sql.NullString        `db:"concurrency_key"`
	CronKey          sql.NullString        `db:"cron_key"`
	RetriedGoodJobID uuid.NullUUID         `db:"retried_good_job_id"`
	CronAt           sql.NullTime          `db:"cron_at"`
	BatchID          uuid.NullUUID         `db:"batch_id"`
	BatchCallbackID  uuid.NullUUID         `db:"batch_callback_id"`
	IsDiscrete       sql.NullBool          `db:"is_discrete"`
	ExecutionsCount  sql.NullInt32         `db:"executions_count"`
	JobClass         sql.NullString        `db:"job_class"`
	ErrorEvent       sql.NullInt16         `db:"error_event"`
	Labels           []string              `db:"labels"`
	LockedByID       uuid.NullUUID         `db:"locked_by_id"`
	LockedAt         sql.NullTime          `db:"locked_at"`
}

type GoodJobBatch struct {
	ID                   uuid.UUID             `db:"id"`
	CreatedAt            time.Time             `db:"created_at"`
	UpdatedAt            time.Time             `db:"updated_at"`
	Description          sql.NullString        `db:"description"`
	SerializedProperties pqtype.NullRawMessage `db:"serialized_properties"`
	OnFinish             sql.NullString        `db:"on_finish"`
	OnSuccess            sql.NullString        `db:"on_success"`
	OnDiscard            sql.NullString        `db:"on_discard"`
	CallbackQueueName    sql.NullString        `db:"callback_queue_name"`
	CallbackPriority     sql.NullInt32         `db:"callback_priority"`
	EnqueuedAt           sql.NullTime          `db:"enqueued_at"`
	DiscardedAt          sql.NullTime          `db:"discarded_at"`
	FinishedAt           sql.NullTime          `db:"finished_at"`
}

type GoodJobExecution struct {
	ID               uuid.UUID             `db:"id"`
	CreatedAt        time.Time             `db:"created_at"`
	UpdatedAt        time.Time             `db:"updated_at"`
	ActiveJobID      uuid.UUID             `db:"active_job_id"`
	JobClass         sql.NullString        `db:"job_class"`
	QueueName        sql.NullString        `db:"queue_name"`
	SerializedParams pqtype.NullRawMessage `db:"serialized_params"`
	ScheduledAt      sql.NullTime          `db:"scheduled_at"`
	FinishedAt       sql.NullTime          `db:"finished_at"`
	Error            sql.NullString        `db:"error"`
	ErrorEvent       sql.NullInt16         `db:"error_event"`
	ErrorBacktrace   []string              `db:"error_backtrace"`
	ProcessID        uuid.NullUUID         `db:"process_id"`
	Duration         sql.NullInt64         `db:"duration"`
}

type GoodJobProcess struct {
	ID        uuid.UUID             `db:"id"`
	CreatedAt time.Time             `db:"created_at"`
	UpdatedAt time.Time             `db:"updated_at"`
	State     pqtype.NullRawMessage `db:"state"`
	LockType  sql.NullInt16         `db:"lock_type"`
}

type GoodJobSetting struct {
	ID        uuid.UUID             `db:"id"`
	CreatedAt time.Time             `db:"created_at"`
	UpdatedAt time.Time             `db:"updated_at"`
	Key       sql.NullString        `db:"key"`
	Value     pqtype.NullRawMessage `db:"value"`
}

type HomeTimelinePost struct {
	ID          uuid.UUID `db:"id"`
	ProfileID   uuid.UUID `db:"profile_id"`
	PostID      uuid.UUID `db:"post_id"`
	PublishedAt time.Time `db:"published_at"`
}

type Link struct {
	ID           uuid.UUID `db:"id"`
	CanonicalUrl string    `db:"canonical_url"`
	Domain       string    `db:"domain"`
	Title        string    `db:"title"`
	ImageUrl     string    `db:"image_url"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

type Notification struct {
	ID              uuid.UUID `db:"id"`
	SourceProfileID uuid.UUID `db:"source_profile_id"`
	TargetProfileID uuid.UUID `db:"target_profile_id"`
	NotifiableType  string    `db:"notifiable_type"`
	NotifiedAt      time.Time `db:"notified_at"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
	NotifiableID    uuid.UUID `db:"notifiable_id"`
}

type OauthAccessGrant struct {
	ID              uuid.UUID    `db:"id"`
	ResourceOwnerID uuid.UUID    `db:"resource_owner_id"`
	UserID          uuid.UUID    `db:"user_id"`
	ApplicationID   uuid.UUID    `db:"application_id"`
	Token           string       `db:"token"`
	ExpiresIn       int32        `db:"expires_in"`
	RedirectUri     string       `db:"redirect_uri"`
	Scopes          string       `db:"scopes"`
	CreatedAt       time.Time    `db:"created_at"`
	RevokedAt       sql.NullTime `db:"revoked_at"`
}

type OauthAccessToken struct {
	ID                   uuid.UUID      `db:"id"`
	ResourceOwnerID      uuid.NullUUID  `db:"resource_owner_id"`
	ApplicationID        uuid.UUID      `db:"application_id"`
	Token                string         `db:"token"`
	RefreshToken         sql.NullString `db:"refresh_token"`
	ExpiresIn            sql.NullInt32  `db:"expires_in"`
	Scopes               sql.NullString `db:"scopes"`
	CreatedAt            time.Time      `db:"created_at"`
	RevokedAt            sql.NullTime   `db:"revoked_at"`
	PreviousRefreshToken string         `db:"previous_refresh_token"`
}

type OauthApplication struct {
	ID           uuid.UUID `db:"id"`
	Name         string    `db:"name"`
	Uid          string    `db:"uid"`
	Secret       string    `db:"secret"`
	RedirectUri  string    `db:"redirect_uri"`
	Scopes       string    `db:"scopes"`
	Confidential bool      `db:"confidential"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

type Post struct {
	ID                 uuid.UUID    `db:"id"`
	ProfileID          uuid.UUID    `db:"profile_id"`
	Content            string       `db:"content"`
	PublishedAt        time.Time    `db:"published_at"`
	CreatedAt          time.Time    `db:"created_at"`
	UpdatedAt          time.Time    `db:"updated_at"`
	DiscardedAt        sql.NullTime `db:"discarded_at"`
	OauthApplicationID uuid.UUID    `db:"oauth_application_id"`
}

type PostLink struct {
	ID        uuid.UUID `db:"id"`
	PostID    uuid.UUID `db:"post_id"`
	LinkID    uuid.UUID `db:"link_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type Profile struct {
	ID            uuid.UUID    `db:"id"`
	OwnerType     string       `db:"owner_type"`
	Atname        string       `db:"atname"`
	Name          string       `db:"name"`
	Description   string       `db:"description"`
	ImageUrl      string       `db:"image_url"`
	JoinedAt      time.Time    `db:"joined_at"`
	CreatedAt     time.Time    `db:"created_at"`
	UpdatedAt     time.Time    `db:"updated_at"`
	DiscardedAt   sql.NullTime `db:"discarded_at"`
	LastPostAt    sql.NullTime `db:"last_post_at"`
	GravatarEmail string       `db:"gravatar_email"`
	GravatarUrl   string       `db:"gravatar_url"`
	AvatarKind    string       `db:"avatar_kind"`
}

type RiverClient struct {
	ID        string          `db:"id"`
	CreatedAt time.Time       `db:"created_at"`
	Metadata  json.RawMessage `db:"metadata"`
	PausedAt  sql.NullTime    `db:"paused_at"`
	UpdatedAt time.Time       `db:"updated_at"`
}

type RiverClientQueue struct {
	RiverClientID    string          `db:"river_client_id"`
	Name             string          `db:"name"`
	CreatedAt        time.Time       `db:"created_at"`
	MaxWorkers       int64           `db:"max_workers"`
	Metadata         json.RawMessage `db:"metadata"`
	NumJobsCompleted int64           `db:"num_jobs_completed"`
	NumJobsRunning   int64           `db:"num_jobs_running"`
	UpdatedAt        time.Time       `db:"updated_at"`
}

type RiverJob struct {
	ID           int64             `db:"id"`
	State        RiverJobState     `db:"state"`
	Attempt      int16             `db:"attempt"`
	MaxAttempts  int16             `db:"max_attempts"`
	AttemptedAt  sql.NullTime      `db:"attempted_at"`
	CreatedAt    time.Time         `db:"created_at"`
	FinalizedAt  sql.NullTime      `db:"finalized_at"`
	ScheduledAt  time.Time         `db:"scheduled_at"`
	Priority     int16             `db:"priority"`
	Args         json.RawMessage   `db:"args"`
	AttemptedBy  []string          `db:"attempted_by"`
	Errors       []json.RawMessage `db:"errors"`
	Kind         string            `db:"kind"`
	Metadata     json.RawMessage   `db:"metadata"`
	Queue        string            `db:"queue"`
	Tags         []string          `db:"tags"`
	UniqueKey    []byte            `db:"unique_key"`
	UniqueStates interface{}       `db:"unique_states"`
}

type RiverLeader struct {
	ElectedAt time.Time `db:"elected_at"`
	ExpiresAt time.Time `db:"expires_at"`
	LeaderID  string    `db:"leader_id"`
	Name      string    `db:"name"`
}

type RiverMigration struct {
	Line      string    `db:"line"`
	Version   int64     `db:"version"`
	CreatedAt time.Time `db:"created_at"`
}

type RiverQueue struct {
	Name      string          `db:"name"`
	CreatedAt time.Time       `db:"created_at"`
	Metadata  json.RawMessage `db:"metadata"`
	PausedAt  sql.NullTime    `db:"paused_at"`
	UpdatedAt time.Time       `db:"updated_at"`
}

type SchemaMigration struct {
	Version string `db:"version"`
}

type Session struct {
	ID         uuid.UUID `db:"id"`
	ActorID    uuid.UUID `db:"actor_id"`
	Token      string    `db:"token"`
	IpAddress  string    `db:"ip_address"`
	UserAgent  string    `db:"user_agent"`
	SignedInAt time.Time `db:"signed_in_at"`
	CreatedAt  time.Time `db:"created_at"`
	UpdatedAt  time.Time `db:"updated_at"`
}

type Stamp struct {
	ID        uuid.UUID `db:"id"`
	ProfileID uuid.UUID `db:"profile_id"`
	PostID    uuid.UUID `db:"post_id"`
	StampedAt time.Time `db:"stamped_at"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type SuggestedFollow struct {
	ID              uuid.UUID    `db:"id"`
	SourceProfileID uuid.UUID    `db:"source_profile_id"`
	TargetProfileID uuid.UUID    `db:"target_profile_id"`
	CheckedAt       sql.NullTime `db:"checked_at"`
	CreatedAt       time.Time    `db:"created_at"`
	UpdatedAt       time.Time    `db:"updated_at"`
}

type User struct {
	ID             uuid.UUID `db:"id"`
	Email          string    `db:"email"`
	PasswordDigest string    `db:"password_digest"`
	Locale         string    `db:"locale"`
	SignedUpAt     time.Time `db:"signed_up_at"`
	CreatedAt      time.Time `db:"created_at"`
	UpdatedAt      time.Time `db:"updated_at"`
	TimeZone       string    `db:"time_zone"`
}

type UserProfile struct {
	ID        uuid.UUID `db:"id"`
	UserID    uuid.UUID `db:"user_id"`
	ProfileID uuid.UUID `db:"profile_id"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}
