// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_links.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const createPostLink = `-- name: CreatePostLink :one
INSERT INTO post_links (post_id, link_id, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, post_id, link_id, created_at, updated_at
`

type CreatePostLinkParams struct {
	PostID uuid.UUID `db:"post_id"`
	LinkID uuid.UUID `db:"link_id"`
}

func (q *Queries) CreatePostLink(ctx context.Context, arg CreatePostLinkParams) (PostLink, error) {
	row := q.db.QueryRowContext(ctx, createPostLink, arg.PostID, arg.LinkID)
	var i PostLink
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.LinkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
