// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package query

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (owner_type, atname, name, description, image_url, joined_at, avatar_kind, gravatar_email, gravatar_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
RETURNING id, owner_type, atname, name, description, image_url, joined_at, avatar_kind, gravatar_email, gravatar_url, discarded_at, last_post_at, created_at, updated_at
`

type CreateProfileParams struct {
	OwnerType     string    `db:"owner_type"`
	Atname        string    `db:"atname"`
	Name          string    `db:"name"`
	Description   string    `db:"description"`
	ImageUrl      string    `db:"image_url"`
	JoinedAt      time.Time `db:"joined_at"`
	AvatarKind    string    `db:"avatar_kind"`
	GravatarEmail string    `db:"gravatar_email"`
	GravatarUrl   string    `db:"gravatar_url"`
}

type CreateProfileRow struct {
	ID            uuid.UUID    `db:"id"`
	OwnerType     string       `db:"owner_type"`
	Atname        string       `db:"atname"`
	Name          string       `db:"name"`
	Description   string       `db:"description"`
	ImageUrl      string       `db:"image_url"`
	JoinedAt      time.Time    `db:"joined_at"`
	AvatarKind    string       `db:"avatar_kind"`
	GravatarEmail string       `db:"gravatar_email"`
	GravatarUrl   string       `db:"gravatar_url"`
	DiscardedAt   sql.NullTime `db:"discarded_at"`
	LastPostAt    sql.NullTime `db:"last_post_at"`
	CreatedAt     time.Time    `db:"created_at"`
	UpdatedAt     time.Time    `db:"updated_at"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (CreateProfileRow, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.OwnerType,
		arg.Atname,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.JoinedAt,
		arg.AvatarKind,
		arg.GravatarEmail,
		arg.GravatarUrl,
	)
	var i CreateProfileRow
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.Atname,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.JoinedAt,
		&i.AvatarKind,
		&i.GravatarEmail,
		&i.GravatarUrl,
		&i.DiscardedAt,
		&i.LastPostAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsProfileByAtname = `-- name: ExistsProfileByAtname :one
SELECT EXISTS(
    SELECT 1 FROM profiles WHERE atname = $1
) AS exists
`

func (q *Queries) ExistsProfileByAtname(ctx context.Context, atname string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsProfileByAtname, atname)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getProfileByAtname = `-- name: GetProfileByAtname :one
SELECT id, owner_type, atname, name, description, image_url, joined_at, avatar_kind, gravatar_email, gravatar_url, discarded_at, last_post_at, created_at, updated_at
FROM profiles
WHERE atname = $1
LIMIT 1
`

type GetProfileByAtnameRow struct {
	ID            uuid.UUID    `db:"id"`
	OwnerType     string       `db:"owner_type"`
	Atname        string       `db:"atname"`
	Name          string       `db:"name"`
	Description   string       `db:"description"`
	ImageUrl      string       `db:"image_url"`
	JoinedAt      time.Time    `db:"joined_at"`
	AvatarKind    string       `db:"avatar_kind"`
	GravatarEmail string       `db:"gravatar_email"`
	GravatarUrl   string       `db:"gravatar_url"`
	DiscardedAt   sql.NullTime `db:"discarded_at"`
	LastPostAt    sql.NullTime `db:"last_post_at"`
	CreatedAt     time.Time    `db:"created_at"`
	UpdatedAt     time.Time    `db:"updated_at"`
}

func (q *Queries) GetProfileByAtname(ctx context.Context, atname string) (GetProfileByAtnameRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByAtname, atname)
	var i GetProfileByAtnameRow
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.Atname,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.JoinedAt,
		&i.AvatarKind,
		&i.GravatarEmail,
		&i.GravatarUrl,
		&i.DiscardedAt,
		&i.LastPostAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, owner_type, atname, name, description, image_url, joined_at, avatar_kind, gravatar_email, gravatar_url, discarded_at, last_post_at, created_at, updated_at
FROM profiles
WHERE id = $1
LIMIT 1
`

type GetProfileByIDRow struct {
	ID            uuid.UUID    `db:"id"`
	OwnerType     string       `db:"owner_type"`
	Atname        string       `db:"atname"`
	Name          string       `db:"name"`
	Description   string       `db:"description"`
	ImageUrl      string       `db:"image_url"`
	JoinedAt      time.Time    `db:"joined_at"`
	AvatarKind    string       `db:"avatar_kind"`
	GravatarEmail string       `db:"gravatar_email"`
	GravatarUrl   string       `db:"gravatar_url"`
	DiscardedAt   sql.NullTime `db:"discarded_at"`
	LastPostAt    sql.NullTime `db:"last_post_at"`
	CreatedAt     time.Time    `db:"created_at"`
	UpdatedAt     time.Time    `db:"updated_at"`
}

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (GetProfileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, id)
	var i GetProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerType,
		&i.Atname,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.JoinedAt,
		&i.AvatarKind,
		&i.GravatarEmail,
		&i.GravatarUrl,
		&i.DiscardedAt,
		&i.LastPostAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
