// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEmailConfirmation(ctx context.Context, arg CreateEmailConfirmationParams) (EmailConfirmation, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteSessionByToken(ctx context.Context, token string) error
	GetActiveEmailConfirmationByID(ctx context.Context, id uuid.UUID) (EmailConfirmation, error)
	GetActorByID(ctx context.Context, id uuid.UUID) (Actor, error)
	GetActorByUserID(ctx context.Context, userID uuid.UUID) (Actor, error)
	GetEmailConfirmationByID(ctx context.Context, id uuid.UUID) (EmailConfirmation, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetSucceededEmailConfirmationByID(ctx context.Context, id uuid.UUID) (EmailConfirmation, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByEmailForSignIn(ctx context.Context, email string) (GetUserByEmailForSignInRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	MarkEmailConfirmationAsSucceeded(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
