// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_limits.sql

package query

import (
	"context"
	"time"
)

const deleteOldRateLimits = `-- name: DeleteOldRateLimits :exec
DELETE FROM rate_limits
WHERE window_start < $1
`

// 指定された時刻より古いRate Limitレコードを削除する
func (q *Queries) DeleteOldRateLimits(ctx context.Context, windowStart time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldRateLimits, windowStart)
	return err
}

const getRateLimitCount = `-- name: GetRateLimitCount :one
SELECT count FROM rate_limits
WHERE key = $1 AND window_start = $2
`

type GetRateLimitCountParams struct {
	Key         string    `db:"key"`
	WindowStart time.Time `db:"window_start"`
}

// 指定されたkeyとウィンドウ開始時刻でのカウントを取得する
func (q *Queries) GetRateLimitCount(ctx context.Context, arg GetRateLimitCountParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getRateLimitCount, arg.Key, arg.WindowStart)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const incrementRateLimit = `-- name: IncrementRateLimit :one
INSERT INTO rate_limits (key, window_start, count, created_at, updated_at)
VALUES ($1, $2, 1, NOW(), NOW())
ON CONFLICT (key, window_start)
DO UPDATE SET
    count = rate_limits.count + 1,
    updated_at = NOW()
RETURNING id, key, window_start, count, created_at, updated_at
`

type IncrementRateLimitParams struct {
	Key         string    `db:"key"`
	WindowStart time.Time `db:"window_start"`
}

// Rate Limit カウンターをインクリメントする（UPSERT）
// 同一のkey + window_startが存在する場合はcountをインクリメント、なければ新規作成
func (q *Queries) IncrementRateLimit(ctx context.Context, arg IncrementRateLimitParams) (RateLimit, error) {
	row := q.db.QueryRowContext(ctx, incrementRateLimit, arg.Key, arg.WindowStart)
	var i RateLimit
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.WindowStart,
		&i.Count,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
