require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-sorbet
  - standard

inherit_gem:
  standard: config/ruby-3.0.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - public/**/*
    - vendor/**/*

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecdescribedclass
RSpec/DescribedClass:
  Enabled: false

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecexamplelength
RSpec/ExampleLength:
  Enabled: false

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecmultipleexpectations
RSpec/MultipleExpectations:
  Enabled: false

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecmultiplememoizedhelpers
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecnestedgroups
RSpec/NestedGroups:
  Enabled: false
