services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - caddy
      - postgresql
    volumes:
      - .:/workspace
      - op-config:/home/developer/.config/op
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/go/.cache/go-build
      - app-gems-data:/mise/installs/ruby/3.3.6/lib/ruby/gems/3.3.0
    ports:
      - "4100:8080" # Go
      - "4101:3000" # Rails
    stdin_open: true
    tty: true
    working_dir: /workspace
    environment:
      - BINDING=0.0.0.0
      - OP_SERVICE_ACCOUNT_TOKEN=${OP_SERVICE_ACCOUNT_TOKEN:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN:-}

  caddy:
    image: caddy:2-alpine
    ports:
      - "4103:8080"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  postgresql:
    image: postgres:18.3
    ports:
      - "4104:5432"
    volumes:
      - postgresql18-data:/var/lib/postgresql:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  chrome:
    image: browserless/chrome:1.61.1-chrome-stable
    ports:
      - "4105:3333"
    environment:
      PORT: 3333
      CONNECTION_TIMEOUT: 600000

volumes:
  app-gems-data:
  go-build-cache:
  go-mod-cache:
  op-config:
  postgresql18-data:
