ARG RUBY_VERSION="3.2.2"
ARG BUNDLER_VERSION="2.5.4"
ARG NODE_VERSION="20.x"

FROM ruby:${RUBY_VERSION}-slim-bookworm

RUN \
  apt update && \
  apt dist-upgrade -yq && \
  apt install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    lsb-release \
    # PostgreSQLやNode.jsのインストールに必要
    gnupg ca-certificates

# PostgreSQLのセットアップ
RUN \
  curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
  echo "deb https://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
  apt update && \
  apt install -y --no-install-recommends \
    libpq-dev \
    postgresql-client-15

# Node.jsのセットアップ
RUN \
  # https://deb.nodesource.com/
  curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION} | bash - && \
  apt install -y --no-install-recommends \
    nodejs \
    npm

# Yarnのセットアップ
RUN \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt update && \
  apt install -y --no-install-recommends \
    yarn

# Chromeをインストールする
RUN \
  # https://developer.chrome.com/blog/chrome-for-testing?hl=ja
  npx @puppeteer/browsers install chrome@stable

RUN gem install bundler -v "${BUNDLER_VERSION}"

WORKDIR /app

CMD ["bash"]
