ARG RUBY_VERSION="3.2.2"
ARG BUNDLER_VERSION="2.5.4"

FROM ruby:${RUBY_VERSION}-slim-bookworm

RUN \
  apt update && \
  apt dist-upgrade -yq && \
  apt install -y --no-install-recommends \
    build-essential \
    curl \
    # PostgreSQLの利用に必要
    postgresql-client libpq-dev

RUN gem install bundler -v "${BUNDLER_VERSION}"

WORKDIR /app

CMD ["bash"]
