# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DeletePostJob`.
# Please instead update this file by running `bin/tapioca dsl DeletePostJob`.

class DeletePostJob
  class << self
    sig { params(post_id: ::String).returns(T.any(DeletePostJob, FalseClass)) }
    def perform_later(post_id:); end

    sig { params(post_id: ::String).void }
    def perform_now(post_id:); end
  end
end
