# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DiscardPostForm`.
# Please instead update this file by running `bin/tapioca dsl DiscardPostForm`.

class DiscardPostForm
  sig { returns(T.nilable(::String)) }
  def target_post_id; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def target_post_id=(value); end
end
