# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NewUserForm`.
# Please instead update this file by running `bin/tapioca dsl NewUserForm`.

class NewUserForm
  sig { returns(T.nilable(::String)) }
  def idname; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def idname=(value); end
end
