# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PostForm`.
# Please instead update this file by running `bin/tapioca dsl PostForm`.

class PostForm
  sig { returns(T.nilable(::String)) }
  def content; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def content=(value); end
end
