# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `FollowForm`.
# Please instead update this file by running `bin/tapioca dsl FollowForm`.


class FollowForm
  sig { returns(T.nilable(::String)) }
  def target_atname; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def target_atname=(value); end
end
