# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LinkDataFetcherForm`.
# Please instead update this file by running `bin/tapioca dsl LinkDataFetcherForm`.


class LinkDataFetcherForm
  sig { returns(T.nilable(::String)) }
  def target_url; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def target_url=(value); end
end
