# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Doorkeeper::ApplicationController`.
# Please instead update this file by running `bin/tapioca dsl Doorkeeper::ApplicationController`.

class Doorkeeper::ApplicationController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
