default: &default
  adapter: mysql2
  ssl_mode: :verify_identity
  sslca: <%= ENV.fetch("MEWST_DATABASE_SSLCA") %>
  host: <%= ENV.fetch("MEWST_DATABASE_HOST") %>
  database: <%= ENV.fetch("MEWST_DATABASE_NAME") %>
  username: <%= ENV.fetch("MEWST_DATABASE_USERNAME") %>
  password: <%= ENV.fetch("MEWST_DATABASE_PASSWORD") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
