# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `V1::PostForm`.
# Please instead update this file by running `bin/tapioca dsl V1::PostForm`.

class V1::PostForm
  sig { returns(T.nilable(::String)) }
  def content; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def content=(value); end
end
