# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `V1::SuggestedFollowForm`.
# Please instead update this file by running `bin/tapioca dsl V1::SuggestedFollowForm`.

class V1::SuggestedFollowForm
  sig { returns(T.nilable(::String)) }
  def target_atname; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def target_atname=(value); end
end
