// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package email_confirmation

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

// EnTextは英語版のメール確認コード通知 (テキスト形式) です。
//
// 段落間の空行を残すため、本文はtempl.Rawを通す。templはリテラルの空白をHTML
// の規則で正規化し、既定の式エスケープは "didn't" を "didn&#39;t" として配信して
// しまう。text/plainパートにはメールアドレスが抜け出せるマークアップが無いため、
// Rawに渡しても安全である (HTMLパートでは引き続きエスケープする)。
func EnText(email, code string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw("Hello "+email+",\n\nYour confirmation code is below.\n\n"+code+"\n\nThis confirmation code will expire in 15 minutes.\n\nIf you didn't request this email, please ignore it.\n\n-- \nMewst\nhttps://mewst.com\n").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
