# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::LanguageServer::Protocol; end
module ::LanguageServer::Protocol::Constant::DiagnosticSeverity; end
module Shrine::Storage::FileSystem; end
module Shrine::Storage::S3; end
module Sidekiq::Process; end
module Sidekiq::SortedEntry; end
module Sidekiq::Web; end
