# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::CommentedPost; end
module Forms::CommentedPost; end
module Forms::SignUp; end
module Google::Protobuf::EnumDescriptor; end
module Resources::Latest::CommentedPost; end
module Resources::Latest::Post::CommentedPost; end
module Services::CreateCommentedPost; end
module Services::SignUp; end
