# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::Tasks::V2::Queue::State`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::Tasks::V2::Queue::State`.

module Google::Cloud::Tasks::V2::Queue::State
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Google::Cloud::Tasks::V2::Queue::State::DISABLED = 3
Google::Cloud::Tasks::V2::Queue::State::PAUSED = 2
Google::Cloud::Tasks::V2::Queue::State::RUNNING = 1
Google::Cloud::Tasks::V2::Queue::State::STATE_UNSPECIFIED = 0
