# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Forms::CommentedPost`.
# Please instead update this file by running `bin/tapioca dsl Forms::CommentedPost`.

class Forms::CommentedPost
  sig { returns(T.nilable(::String)) }
  def comment; end

  sig { params(value: T.nilable(::String)).returns(T.nilable(::String)) }
  def comment=(value); end
end
