# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `committee` gem.
# Please instead update this file by running `bin/tapioca gem committee`.


# Don't Support OpenAPI3
# Stub is not yet supported in OpenAPI 3
#
# pkg:gem/committee#lib/committee/version.rb:3
module Committee
  class << self
    # pkg:gem/committee#lib/committee.rb:12
    def debug?; end

    # pkg:gem/committee#lib/committee.rb:16
    def log_debug(message); end

    # pkg:gem/committee#lib/committee.rb:20
    def need_good_option(message); end

    # pkg:gem/committee#lib/committee.rb:24
    def warn_deprecated_until_6(cond, message); end
  end
end

# pkg:gem/committee#lib/committee/errors.rb:7
class Committee::BadRequest < ::Committee::Error; end

# pkg:gem/committee#lib/committee/bin/committee_stub.rb:6
module Committee::Bin; end

# CommitteeStub internalizes the functionality of bin/committee-stub so
# that we can test code that would otherwise be difficult to get at in an
# executable.
#
# pkg:gem/committee#lib/committee/bin/committee_stub.rb:10
class Committee::Bin::CommitteeStub
  # Gets a Rack app suitable for use as a stub.
  #
  # pkg:gem/committee#lib/committee/bin/committee_stub.rb:12
  def get_app(schema, options); end

  # Gets an option parser for command line arguments.
  #
  # pkg:gem/committee#lib/committee/bin/committee_stub.rb:32
  def get_options_parser; end
end

# pkg:gem/committee#lib/committee/drivers.rb:6
module Committee::Drivers
  class << self
    # Gets a driver instance from the specified name. Raises ArgumentError for
    # an unknown driver name.
    #
    # pkg:gem/committee#lib/committee/drivers.rb:9
    def driver_from_name(name); end

    # load and build drive from Hash object
    # @param [Hash] hash
    # @return [Committee::Driver]
    #
    # pkg:gem/committee#lib/committee/drivers.rb:57
    def load_from_data(hash, schema_path = T.unsafe(nil), parser_options: T.unsafe(nil)); end

    # load and build drive from file
    # @param [String] schema_path
    # @return [Committee::Driver]
    #
    # pkg:gem/committee#lib/committee/drivers.rb:40
    def load_from_file(schema_path, parser_options: T.unsafe(nil)); end

    # load and build drive from JSON file
    # @param [String] schema_path
    # @return [Committee::Driver]
    #
    # pkg:gem/committee#lib/committee/drivers.rb:25
    def load_from_json(schema_path, parser_options: T.unsafe(nil)); end

    # load and build drive from YAML file
    # @param [String] schema_path
    # @return [Committee::Driver]
    #
    # pkg:gem/committee#lib/committee/drivers.rb:32
    def load_from_yaml(schema_path, parser_options: T.unsafe(nil)); end

    private

    # pkg:gem/committee#lib/committee/drivers.rb:90
    def cache_key(schema_path, parser_options); end
  end
end

# Driver is a base class for driver implementations.
#
# pkg:gem/committee#lib/committee/drivers/driver.rb:6
class Committee::Drivers::Driver
  # Use GET request body to request parameter (request body merge to parameter)
  #
  # pkg:gem/committee#lib/committee/drivers/driver.rb:13
  def default_allow_get_body; end

  # Whether parameters that were form-encoded will be coerced by default.
  #
  # pkg:gem/committee#lib/committee/drivers/driver.rb:8
  def default_coerce_form_params; end

  # Whether parameters in a request's path will be considered and coerced
  # by default.
  #
  # pkg:gem/committee#lib/committee/drivers/driver.rb:19
  def default_path_params; end

  # Whether parameters in a request's query string will be considered and
  # coerced by default.
  #
  # pkg:gem/committee#lib/committee/drivers/driver.rb:25
  def default_query_params; end

  # pkg:gem/committee#lib/committee/drivers/driver.rb:29
  def name; end

  # Parses an API schema and builds a set of route definitions for use with
  # Committee.
  #
  # The expected input format is a data hash with keys as strings (as
  # opposed to symbols) like the kind produced by JSON.parse or YAML.load.
  #
  # pkg:gem/committee#lib/committee/drivers/driver.rb:38
  def parse(data); end

  # pkg:gem/committee#lib/committee/drivers/driver.rb:42
  def schema_class; end
end

# pkg:gem/committee#lib/committee/drivers/hyper_schema.rb:5
module Committee::Drivers::HyperSchema; end

# pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:6
class Committee::Drivers::HyperSchema::Driver < ::Committee::Drivers::Driver
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:16
  def default_allow_get_body; end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:7
  def default_coerce_date_times; end

  # Whether parameters that were form-encoded will be coerced by default.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:12
  def default_coerce_form_params; end

  # Whether parameters in a request's path will be considered and coerced by
  # default.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:22
  def default_path_params; end

  # Whether parameters in a request's query string will be considered and
  # coerced by default.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:28
  def default_query_params; end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:32
  def default_validate_success_only; end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:36
  def name; end

  # Parses an API schema and builds a set of route definitions for use with
  # Committee.
  #
  # The expected input format is a data hash with keys as strings (as opposed
  # to symbols) like the kind produced by JSON.parse or YAML.load.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:45
  def parse(schema); end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:62
  def schema_class; end

  private

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:68
  def build_routes(hyper_schema); end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:91
  def href_to_regex(href); end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/driver.rb:95
  def parse_link(link); end
end

# Link abstracts an API link specifically for JSON hyper-schema.
#
# For most operations, it's a simple pass through to a
# JsonSchema::Schema::Link, but implements some exotic behavior in a few
# places.
#
# pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:11
class Committee::Drivers::HyperSchema::Link
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:12
  def initialize(hyper_schema_link); end

  # The link's input media type. i.e. How requests should be encoded.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:17
  def enc_type; end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:21
  def href; end

  # The link's output media type. i.e. How responses should be encoded.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:26
  def media_type; end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:30
  def method; end

  # Passes through a link's parent resource. Note that this is *not* part
  # of the Link interface and is here to support a legacy Heroku-ism
  # behavior that allowed a link tagged with rel=instances to imply that a
  # list will be returned.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:38
  def parent; end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:42
  def rel; end

  # The link's input schema. i.e. How we validate an endpoint's incoming
  # parameters.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:48
  def schema; end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:52
  def status_success; end

  # The link's output schema. i.e. How we validate an endpoint's response
  # data.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:58
  def target_schema; end

  private

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:64
  def hyper_schema_link; end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/link.rb:64
  def hyper_schema_link=(_arg0); end
end

# pkg:gem/committee#lib/committee/drivers/hyper_schema/schema.rb:6
class Committee::Drivers::HyperSchema::Schema < ::Committee::Drivers::Schema
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/schema.rb:15
  def build_router(options); end

  # A link back to the derivative instance of Committee::Drivers::Driver
  # that create this schema.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/schema.rb:9
  def driver; end

  # A link back to the derivative instance of Committee::Drivers::Driver
  # that create this schema.
  #
  # pkg:gem/committee#lib/committee/drivers/hyper_schema/schema.rb:9
  def driver=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/schema.rb:11
  def routes; end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/schema.rb:11
  def routes=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/hyper_schema/schema.rb:13
  def validator_option; end
end

# pkg:gem/committee#lib/committee/drivers/open_api_2.rb:5
module Committee::Drivers::OpenAPI2; end

# pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:6
class Committee::Drivers::OpenAPI2::Driver < ::Committee::Drivers::Driver
  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:16
  def default_allow_get_body; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:7
  def default_coerce_date_times; end

  # Whether parameters that were form-encoded will be coerced by default.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:12
  def default_coerce_form_params; end

  # Whether parameters in a request's path will be considered and coerced by
  # default.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:22
  def default_path_params; end

  # Whether parameters in a request's query string will be considered and
  # coerced by default.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:28
  def default_query_params; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:32
  def default_validate_success_only; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:36
  def name; end

  # Parses an API schema and builds a set of route definitions for use with
  # Committee.
  #
  # The expected input format is a data hash with keys as strings (as opposed
  # to symbols) like the kind produced by JSON.parse or YAML.load.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:45
  def parse(data); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:74
  def schema_class; end

  private

  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:86
  def find_best_fit_response(link_data); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:103
  def href_to_regex(href); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:107
  def parse_definitions!(data); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:130
  def parse_routes!(data, schema, store); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:224
  def rewrite_references(schema); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:217
  def rewrite_references_and_parse(schemas_data, store); end
end

# pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:80
Committee::Drivers::OpenAPI2::Driver::DEFINITIONS_PSEUDO_URI = T.let(T.unsafe(nil), String)

# These are fields that the OpenAPI 2 spec considers mandatory to be
# included in the document's top level.
#
# pkg:gem/committee#lib/committee/drivers/open_api_2/driver.rb:84
Committee::Drivers::OpenAPI2::Driver::REQUIRED_FIELDS = T.let(T.unsafe(nil), Array)

# pkg:gem/committee#lib/committee/drivers/open_api_2/header_schema_builder.rb:6
class Committee::Drivers::OpenAPI2::HeaderSchemaBuilder < ::Committee::Drivers::OpenAPI2::SchemaBuilder
  # pkg:gem/committee#lib/committee/drivers/open_api_2/header_schema_builder.rb:7
  def call; end
end

# Link abstracts an API link specifically for OpenAPI 2.
#
# pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:7
class Committee::Drivers::OpenAPI2::Link
  # The link's input media type. i.e. How requests should be encoded.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:9
  def enc_type; end

  # The link's input media type. i.e. How requests should be encoded.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:9
  def enc_type=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:28
  def header_schema; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:28
  def header_schema=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:11
  def href; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:11
  def href=(_arg0); end

  # The link's output media type. i.e. How responses should be encoded.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:14
  def media_type; end

  # The link's output media type. i.e. How responses should be encoded.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:14
  def media_type=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:16
  def method; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:16
  def method=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:30
  def rel; end

  # The link's input schema. i.e. How we validate an endpoint's incoming
  # parameters.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:20
  def schema; end

  # The link's input schema. i.e. How we validate an endpoint's incoming
  # parameters.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:20
  def schema=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:22
  def status_success; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:22
  def status_success=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:34
  def target_schema; end

  # The link's output schema. i.e. How we validate an endpoint's response
  # data.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:26
  def target_schemas; end

  # The link's output schema. i.e. How we validate an endpoint's response
  # data.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/link.rb:26
  def target_schemas=(_arg0); end
end

# ParameterSchemaBuilder converts OpenAPI 2 link parameters, which are not
# quite JSON schemas (but will be in OpenAPI 3) into synthetic schemas that
# we can use to do some basic request validation.
#
# pkg:gem/committee#lib/committee/drivers/open_api_2/parameter_schema_builder.rb:9
class Committee::Drivers::OpenAPI2::ParameterSchemaBuilder < ::Committee::Drivers::OpenAPI2::SchemaBuilder
  # Returns a tuple of (schema, schema_data) where only one of the two
  # values is present. This is either a full schema that's ready to go _or_
  # a hash of unparsed schema data.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/parameter_schema_builder.rb:13
  def call; end
end

# pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:6
class Committee::Drivers::OpenAPI2::Schema < ::Committee::Drivers::Schema
  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:7
  def base_path; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:7
  def base_path=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:19
  def build_router(options); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:8
  def consumes; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:8
  def consumes=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:14
  def definitions; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:14
  def definitions=(_arg0); end

  # A link back to the derivative instance of Committee::Drivers::Driver
  # that create this schema.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:12
  def driver; end

  # A link back to the derivative instance of Committee::Drivers::Driver
  # that create this schema.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:12
  def driver=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:15
  def produces; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:15
  def produces=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:16
  def routes; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:16
  def routes=(_arg0); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema.rb:17
  def validator_option; end
end

# pkg:gem/committee#lib/committee/drivers/open_api_2/schema_builder.rb:6
class Committee::Drivers::OpenAPI2::SchemaBuilder
  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema_builder.rb:7
  def initialize(link_data); end

  private

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema_builder.rb:17
  def check_required_fields!(param_data); end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema_builder.rb:15
  def link_data; end

  # pkg:gem/committee#lib/committee/drivers/open_api_2/schema_builder.rb:15
  def link_data=(_arg0); end
end

# pkg:gem/committee#lib/committee/drivers/open_api_2/schema_builder.rb:13
Committee::Drivers::OpenAPI2::SchemaBuilder::LINK_REQUIRED_FIELDS = T.let(T.unsafe(nil), Array)

# pkg:gem/committee#lib/committee/drivers/open_api_3.rb:5
module Committee::Drivers::OpenAPI3; end

# pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:6
class Committee::Drivers::OpenAPI3::Driver < ::Committee::Drivers::Driver
  # pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:17
  def default_allow_get_body; end

  # pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:7
  def default_coerce_date_times; end

  # Historically named for form params, but in OpenAPI 3 this flag controls
  # request body coercion more generally.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:13
  def default_coerce_form_params; end

  # Whether to deserialize parameters based on OpenAPI 3 style/explode settings
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:38
  def default_deserialize_parameters; end

  # Whether parameters in a request's path will be considered and coerced by
  # default.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:23
  def default_path_params; end

  # Whether parameters in a request's query string will be considered and
  # coerced by default.
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:29
  def default_query_params; end

  # pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:33
  def default_validate_success_only; end

  # pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:42
  def name; end

  # @return [Committee::Drivers::OpenAPI3::Schema]
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:47
  def parse(open_api); end

  # pkg:gem/committee#lib/committee/drivers/open_api_3/driver.rb:51
  def schema_class; end
end

# pkg:gem/committee#lib/committee/drivers/open_api_3/schema.rb:6
class Committee::Drivers::OpenAPI3::Schema < ::Committee::Drivers::Schema
  # @!attribute [r] open_api
  #   @return [OpenAPIParser::Schemas::OpenAPI]
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_3/schema.rb:13
  def initialize(driver, open_api); end

  # pkg:gem/committee#lib/committee/drivers/open_api_3/schema.rb:26
  def build_router(options); end

  # pkg:gem/committee#lib/committee/drivers/open_api_3/schema.rb:22
  def driver; end

  # pkg:gem/committee#lib/committee/drivers/open_api_3/schema.rb:7
  def open_api; end

  # OpenAPI3 only
  #
  # pkg:gem/committee#lib/committee/drivers/open_api_3/schema.rb:32
  def operation_object(path, method); end

  # pkg:gem/committee#lib/committee/drivers/open_api_3/schema.rb:18
  def supports_stub?; end

  # pkg:gem/committee#lib/committee/drivers/open_api_3/schema.rb:8
  def validator_option; end
end

# Schema is a base class for driver schema implementations.
#
# pkg:gem/committee#lib/committee/drivers/schema.rb:6
class Committee::Drivers::Schema
  # pkg:gem/committee#lib/committee/drivers/schema.rb:13
  def build_router(options); end

  # A link back to the derivative instance of Committee::Drivers::Driver
  # that create this schema.
  #
  # pkg:gem/committee#lib/committee/drivers/schema.rb:9
  def driver; end

  # Stubs are supported in JSON Hyper-Schema and OpenAPI 2, but not yet in OpenAPI 3
  #
  # pkg:gem/committee#lib/committee/drivers/schema.rb:18
  def supports_stub?; end
end

# pkg:gem/committee#lib/committee/errors.rb:4
class Committee::Error < ::StandardError; end

# pkg:gem/committee#lib/committee/errors.rb:10
class Committee::InvalidRequest < ::Committee::Error
  # pkg:gem/committee#lib/committee/errors.rb:13
  def initialize(error_message = T.unsafe(nil), original_error: T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/errors.rb:11
  def original_error; end
end

# pkg:gem/committee#lib/committee/errors.rb:19
class Committee::InvalidResponse < ::Committee::Error
  # pkg:gem/committee#lib/committee/errors.rb:22
  def initialize(error_message = T.unsafe(nil), original_error: T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/errors.rb:20
  def original_error; end
end

# pkg:gem/committee#lib/committee/middleware.rb:4
module Committee::Middleware; end

# pkg:gem/committee#lib/committee/middleware/base.rb:5
class Committee::Middleware::Base
  # pkg:gem/committee#lib/committee/middleware/base.rb:6
  def initialize(app, options = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/middleware/base.rb:21
  def call(env); end

  private

  # Subclasses should override this method to use their specific Options class
  #
  # pkg:gem/committee#lib/committee/middleware/base.rb:54
  def build_options(options); end

  # pkg:gem/committee#lib/committee/middleware/base.rb:58
  def build_schema_validator(request); end

  class << self
    # pkg:gem/committee#lib/committee/middleware/base.rb:32
    def get_schema(options); end
  end
end

# pkg:gem/committee#lib/committee/middleware/options.rb:5
module Committee::Middleware::Options; end

# pkg:gem/committee#lib/committee/middleware/options/base.rb:6
class Committee::Middleware::Options::Base
  # pkg:gem/committee#lib/committee/middleware/options/base.rb:20
  def initialize(options = T.unsafe(nil)); end

  # Allow Hash-like access for backward compatibility
  #
  # pkg:gem/committee#lib/committee/middleware/options/base.rb:42
  def [](key); end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:15
  def accept_request_filter; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:10
  def error_class; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:11
  def error_handler; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:46
  def fetch(key, default = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:13
  def ignore_error; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:14
  def prefix; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:12
  def raise_error; end

  # Common options
  #
  # pkg:gem/committee#lib/committee/middleware/options/base.rb:8
  def schema; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:9
  def schema_path; end

  # Schema loading options
  #
  # pkg:gem/committee#lib/committee/middleware/options/base.rb:18
  def strict_reference_validation; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:50
  def to_h; end

  private

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:100
  def build_hash; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:69
  def validate!; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:94
  def validate_accept_request_filter!; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:82
  def validate_error_class!; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:76
  def validate_error_handler!; end

  # pkg:gem/committee#lib/committee/middleware/options/base.rb:88
  def validate_schema_source!; end

  class << self
    # Create an Option object from Hash options
    # Returns the object as-is if already an Option object
    #
    # pkg:gem/committee#lib/committee/middleware/options/base.rb:56
    def from(options); end
  end
end

# pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:6
class Committee::Middleware::Options::RequestValidation < ::Committee::Middleware::Options::Base
  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:34
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:26
  def allow_blank_structures; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:27
  def allow_empty_date_and_datetime; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:14
  def allow_form_params; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:16
  def allow_get_body; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:17
  def allow_non_get_query_params; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:15
  def allow_query_params; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:18
  def check_content_type; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:19
  def check_header; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:9
  def coerce_date_times; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:11
  def coerce_form_params; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:12
  def coerce_path_params; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:13
  def coerce_query_params; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:10
  def coerce_recursive; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:29
  def deserialize_parameters; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:24
  def headers_key; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:20
  def optimistic_json; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:28
  def parameter_overwrite_by_rails_rule; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:25
  def params_key; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:23
  def path_hash_key; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:22
  def query_hash_key; end

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:21
  def request_body_hash_key; end

  # RequestValidation specific options
  #
  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:8
  def strict; end

  private

  # pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:74
  def build_hash; end
end

# Default values
#
# pkg:gem/committee#lib/committee/middleware/options/request_validation.rb:32
Committee::Middleware::Options::RequestValidation::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/committee#lib/committee/middleware/options/response_validation.rb:6
class Committee::Middleware::Options::ResponseValidation < ::Committee::Middleware::Options::Base
  # pkg:gem/committee#lib/committee/middleware/options/response_validation.rb:17
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/middleware/options/response_validation.rb:11
  def coerce_response_values; end

  # pkg:gem/committee#lib/committee/middleware/options/response_validation.rb:10
  def parse_response_by_content_type; end

  # pkg:gem/committee#lib/committee/middleware/options/response_validation.rb:12
  def streaming_content_parsers; end

  # ResponseValidation specific options
  #
  # pkg:gem/committee#lib/committee/middleware/options/response_validation.rb:8
  def strict; end

  # pkg:gem/committee#lib/committee/middleware/options/response_validation.rb:9
  def validate_success_only; end

  private

  # pkg:gem/committee#lib/committee/middleware/options/response_validation.rb:40
  def build_hash; end

  # pkg:gem/committee#lib/committee/middleware/options/response_validation.rb:34
  def validate_response_validation_options!; end
end

# Default values
#
# pkg:gem/committee#lib/committee/middleware/options/response_validation.rb:15
Committee::Middleware::Options::ResponseValidation::DEFAULTS = T.let(T.unsafe(nil), Hash)

# pkg:gem/committee#lib/committee/middleware/request_validation.rb:5
class Committee::Middleware::RequestValidation < ::Committee::Middleware::Base
  # pkg:gem/committee#lib/committee/middleware/request_validation.rb:6
  def initialize(app, options = T.unsafe(nil)); end

  private

  # pkg:gem/committee#lib/committee/middleware/request_validation.rb:14
  def build_options(options); end

  # pkg:gem/committee#lib/committee/middleware/request_validation.rb:18
  def handle(request); end

  # pkg:gem/committee#lib/committee/middleware/request_validation.rb:43
  def handle_exception(e, env); end
end

# pkg:gem/committee#lib/committee/middleware/response_validation.rb:5
class Committee::Middleware::ResponseValidation < ::Committee::Middleware::Base
  # pkg:gem/committee#lib/committee/middleware/response_validation.rb:8
  def initialize(app, options = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/middleware/response_validation.rb:15
  def handle(request); end

  # pkg:gem/committee#lib/committee/middleware/response_validation.rb:6
  def validate_success_only; end

  private

  # pkg:gem/committee#lib/committee/middleware/response_validation.rb:66
  def build_options(options); end

  # pkg:gem/committee#lib/committee/middleware/response_validation.rb:83
  def handle_exception(e, env); end

  # pkg:gem/committee#lib/committee/middleware/response_validation.rb:77
  def retrieve_streaming_content_parser(headers); end

  # pkg:gem/committee#lib/committee/middleware/response_validation.rb:70
  def validate(request, status, headers, response, streaming_content_parser = T.unsafe(nil)); end

  class << self
    # pkg:gem/committee#lib/committee/middleware/response_validation.rb:50
    def validate?(status, validate_success_only); end
  end
end

# pkg:gem/committee#lib/committee/middleware/stub.rb:7
class Committee::Middleware::Stub < ::Committee::Middleware::Base
  # pkg:gem/committee#lib/committee/middleware/stub.rb:8
  def initialize(app, options = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/middleware/stub.rb:24
  def handle(request); end

  private

  # pkg:gem/committee#lib/committee/middleware/stub.rb:60
  def cache(link); end
end

# pkg:gem/committee#lib/committee/errors.rb:28
class Committee::NotFound < ::Committee::Error; end

# pkg:gem/committee#lib/committee/errors.rb:34
class Committee::OpenAPI3Unsupported < ::Committee::Error; end

# pkg:gem/committee#lib/committee/errors.rb:37
class Committee::ParameterDeserializationError < ::Committee::InvalidRequest
  # pkg:gem/committee#lib/committee/errors.rb:40
  def initialize(param_name, style, raw_value, message); end

  # pkg:gem/committee#lib/committee/errors.rb:38
  def parameter_name; end

  # pkg:gem/committee#lib/committee/errors.rb:38
  def raw_value; end

  # pkg:gem/committee#lib/committee/errors.rb:38
  def style; end
end

# pkg:gem/committee#lib/committee/errors.rb:31
class Committee::ReferenceNotFound < ::Committee::Error; end

# pkg:gem/committee#lib/committee/request_unpacker.rb:4
class Committee::RequestUnpacker
  # pkg:gem/committee#lib/committee/request_unpacker.rb:23
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/request_unpacker.rb:73
  def unpack_headers(request); end

  # pkg:gem/committee#lib/committee/request_unpacker.rb:61
  def unpack_query_params(request); end

  # return params and is_form_params
  #
  # pkg:gem/committee#lib/committee/request_unpacker.rb:33
  def unpack_request_params(request); end

  private

  # pkg:gem/committee#lib/committee/request_unpacker.rb:87
  def parse_json(request); end

  class << self
    # Enable string or symbol key access to the nested params hash.
    #
    # (Copied from Sinatra)
    #
    # pkg:gem/committee#lib/committee/request_unpacker.rb:9
    def indifferent_params(object); end
  end
end

# pkg:gem/committee#lib/committee/schema_validator.rb:4
module Committee::SchemaValidator
  class << self
    # @param [String] prefix
    # @return [Regexp]
    #
    # pkg:gem/committee#lib/committee/schema_validator.rb:19
    def build_prefix_regexp(prefix); end

    # pkg:gem/committee#lib/committee/schema_validator.rb:12
    def json_media_type?(content_type); end

    # pkg:gem/committee#lib/committee/schema_validator.rb:8
    def request_media_type(request); end
  end
end

# pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:5
class Committee::SchemaValidator::HyperSchema
  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:8
  def initialize(router, request, validator_option); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:6
  def link; end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:47
  def link_exist?; end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:6
  def param_matches; end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:13
  def request_validate(request); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:21
  def response_validate(status, headers, response, _test_method = T.unsafe(nil), custom_body_parser = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:6
  def validator_option; end

  private

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:91
  def coerce_form_params(parameter); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:53
  def coerce_path_params; end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:60
  def coerce_query_params(request); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:103
  def parameter_coerce!(request, link, coerce_key); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:97
  def request_schema_validation(request); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema.rb:67
  def request_unpack(request); end
end

# pkg:gem/committee#lib/committee/schema_validator/hyper_schema/parameter_coercer.rb:6
class Committee::SchemaValidator::HyperSchema::ParameterCoercer
  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/parameter_coercer.rb:7
  def initialize(params, schema, options = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/parameter_coercer.rb:15
  def call!; end

  private

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/parameter_coercer.rb:53
  def coerce_array_data!(original_val, schema); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/parameter_coercer.rb:21
  def coerce_object!(hash, schema); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/parameter_coercer.rb:39
  def coerce_value!(original_val, s); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/parameter_coercer.rb:69
  def parse_date_time(original_val); end
end

# pkg:gem/committee#lib/committee/schema_validator/hyper_schema/request_validator.rb:6
class Committee::SchemaValidator::HyperSchema::RequestValidator
  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/request_validator.rb:7
  def initialize(link, options = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/request_validator.rb:13
  def call(request, params, headers); end

  private

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/request_validator.rb:34
  def check_content_type!(request, data); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/request_validator.rb:43
  def empty_request?(request); end
end

# pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_generator.rb:6
class Committee::SchemaValidator::HyperSchema::ResponseGenerator
  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_generator.rb:7
  def call(link); end

  private

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_generator.rb:41
  def generate_properties(link, schema); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_generator.rb:80
  def legacy_hyper_schema_rel?(link); end

  # Gets the target schema of a link. This is normally just the standard
  # response schema, but we allow some legacy behavior for hyper-schema links
  # tagged with rel=instances to instead use the schema of their parent
  # resource.
  #
  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_generator.rb:90
  def target_schema(link); end
end

# These are basic types that are part of the JSON schema for which we'll
# emit zero values when generating a response. For a schema that allows
# multiple of the types in the list, types are preferred in the order in
# which they're defined.
#
# pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_generator.rb:31
Committee::SchemaValidator::HyperSchema::ResponseGenerator::SCALAR_TYPES = T.let(T.unsafe(nil), Hash)

# pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_validator.rb:6
class Committee::SchemaValidator::HyperSchema::ResponseValidator
  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_validator.rb:9
  def initialize(link, options = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_validator.rb:7
  def allow_blank_structures; end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_validator.rb:25
  def call(status, headers, data); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_validator.rb:76
  def validate?(status); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_validator.rb:7
  def validate_success_only; end

  private

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_validator.rb:100
  def check_content_type!(response); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_validator.rb:108
  def legacy_hyper_schema_rel?(link); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_validator.rb:91
  def response_media_type(response); end

  # Gets the target schema of a link. This is normally just the standard
  # response schema, but we allow some legacy behavior for hyper-schema links
  # tagged with rel=instances to instead use the schema of their parent
  # resource.
  #
  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/response_validator.rb:118
  def target_schema(link); end
end

# pkg:gem/committee#lib/committee/schema_validator/hyper_schema/router.rb:6
class Committee::SchemaValidator::HyperSchema::Router
  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/router.rb:7
  def initialize(schema, validator_option); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/router.rb:40
  def build_schema_validator(request); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/router.rb:23
  def find_link(method, path); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/router.rb:36
  def find_request_link(request); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/router.rb:15
  def includes?(path); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/router.rb:19
  def includes_request?(request); end
end

# StringParamsCoercer takes parameters that are specified over a medium that
# can only accept strings (for example in a URL path or in query parameters)
# and attempts to coerce them into known types based of a link's schema
# definition.
#
# Currently supported types: null, integer, number and boolean.
#
# +call+ returns a hash of all params which could be coerced - coercion
# errors are simply ignored and expected to be handled later by schema
# validation.
#
# pkg:gem/committee#lib/committee/schema_validator/hyper_schema/string_params_coercer.rb:16
class Committee::SchemaValidator::HyperSchema::StringParamsCoercer
  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/string_params_coercer.rb:17
  def initialize(query_hash, schema, options = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/string_params_coercer.rb:24
  def call!; end

  private

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/string_params_coercer.rb:87
  def coerce_array_data!(original_val, schema); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/string_params_coercer.rb:30
  def coerce_object!(hash, schema); end

  # pkg:gem/committee#lib/committee/schema_validator/hyper_schema/string_params_coercer.rb:48
  def coerce_value!(original_val, s); end
end

# pkg:gem/committee#lib/committee/schema_validator.rb:5
Committee::SchemaValidator::JSON_MEDIA_TYPE_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:5
class Committee::SchemaValidator::OpenAPI3
  # @param [Committee::SchemaValidator::Option] validator_option
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:7
  def initialize(router, request, validator_option); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:49
  def link_exist?; end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:14
  def request_validate(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:23
  def response_validate(status, headers, response, test_method = T.unsafe(nil), custom_body_parser = T.unsafe(nil)); end

  private

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:76
  def body_params(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:57
  def coerce_path_params; end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:113
  def copy_coerced_data_to_params(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:80
  def header(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:68
  def path_params(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:72
  def query_params(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:61
  def request_schema_validation(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:84
  def request_unpack(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3.rb:55
  def validator_option; end
end

# pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:6
class Committee::SchemaValidator::OpenAPI3::OperationWrapper
  # # @param request_operation [OpenAPIParser::RequestOperation]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:8
  def initialize(request_operation); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:24
  def coerce_path_parameter(validator_option); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:20
  def http_method; end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:56
  def optional_body?; end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:16
  def original_path; end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:12
  def path_params; end

  # @return [Array<String>] names of query parameters defined in the schema
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:79
  def query_parameter_names; end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:70
  def request_content_types; end

  # Expose request_operation for parameter deserialization
  # @return [OpenAPIParser::RequestOperation]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:76
  def request_operation; end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:60
  def valid_request_content_type?(content_type); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:43
  def validate_request_params(path_params, query_params, body_params, headers, validator_option); end

  # @param [Boolean] strict when not content_type or status code definition, raise error
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:35
  def validate_response_params(status_code, headers, response_data, strict, check_header, validator_options: T.unsafe(nil)); end

  private

  # @return [OpenAPIParser::SchemaValidator::Options]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:88
  def build_openapi_parser_body_option(validator_option); end

  # @return [OpenAPIParser::SchemaValidator::Options]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:103
  def build_openapi_parser_option(validator_option, coerce_value); end

  # @return [OpenAPIParser::SchemaValidator::Options]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:93
  def build_openapi_parser_path_option(validator_option); end

  # @return [OpenAPIParser::SchemaValidator::Options]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:98
  def build_openapi_parser_request_parameter_option(validator_option); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:166
  def response_validate_options(strict, check_header, validator_options: T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:115
  def validate_get_request_params(path_params, query_params, headers, validator_option); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:155
  def validate_no_unknown_query_params(query_params); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:133
  def validate_path_and_query_params(path_params, query_params, headers, validator_option); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/operation_wrapper.rb:122
  def validate_post_request_params(path_params, query_params, body_params, headers, validator_option); end
end

# Deserializes request parameters based on OpenAPI 3 parameter style and explode settings
#
# @see https://swagger.io/docs/specification/serialization/
# @see https://spec.openapis.org/oas/latest.html#parameter-object
#
# pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:12
class Committee::SchemaValidator::OpenAPI3::ParameterDeserializer
  # @param [OpenAPIParser::RequestOperation] request_operation
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:14
  def initialize(request_operation); end

  # Deserialize header parameters
  # @param [Hash] raw_headers Raw headers
  # @return [Hash] Deserialized headers according to OpenAPI schema
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:36
  def deserialize_headers(raw_headers); end

  # Deserialize path parameters
  # @param [Hash] raw_params Raw path parameters
  # @return [Hash] Deserialized parameters according to OpenAPI schema
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:29
  def deserialize_path_params(raw_params); end

  # Deserialize query parameters
  # @param [Hash] raw_params Raw query parameters from Rack
  # @return [Hash] Deserialized parameters according to OpenAPI schema
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:22
  def deserialize_query_params(raw_params); end

  private

  # Collect object properties from separate parameters (form explode=true)
  # @param [OpenAPIParser::Schemas::Schema] schema
  # @param [Hash] raw_params
  # @param [String] param_name Original parameter name (not used in exploded form)
  # @return [Hash, nil] Collected object properties
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:288
  def collect_object_properties(schema, raw_params, param_name); end

  # Convert a hash to an indifferent hash (supports both string and symbol keys)
  # @param [Hash] hash
  # @return [Committee::Utils::IndifferentHash]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:105
  def convert_to_indifferent_hash(hash); end

  # Get default explode setting for a style
  # @param [String] style Parameter style
  # @return [Boolean] Default explode value
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:217
  def default_explode(style); end

  # Get default style for a parameter location
  # @param [String] location Parameter location
  # @return [String] Default style
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:203
  def default_style(location); end

  # Deserialize deep object style (query parameters only)
  # Example: ?filter[role]=admin&filter[status]=active → { filter: { role: "admin", status: "active" } }
  # @param [OpenAPIParser::Schemas::Parameter] param_def
  # @param [Hash] raw_params
  # @return [Hash, nil] Deserialized object
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:326
  def deserialize_deep_object(param_def, raw_params); end

  # Deserialize form-style array
  # @param [String] param_name
  # @param [OpenAPIParser::Schemas::Schema] schema
  # @param [Hash] raw_params
  # @param [Boolean] explode
  # @return [Array, nil] Deserialized array
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:268
  def deserialize_form_array(param_name, schema, raw_params, explode); end

  # Deserialize form-style object
  # @param [String] param_name
  # @param [OpenAPIParser::Schemas::Schema] schema
  # @param [Hash] raw_params
  # @param [Boolean] explode
  # @return [Hash, nil] Deserialized object
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:249
  def deserialize_form_object(param_name, schema, raw_params, explode); end

  # Deserialize form style parameter
  # Default for query and cookie parameters
  # @param [OpenAPIParser::Schemas::Parameter] param_def
  # @param [Hash] raw_params
  # @param [Boolean] explode
  # @return [Object] Deserialized value
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:227
  def deserialize_form_style(param_def, raw_params, explode); end

  # Deserialize label style (path parameters)
  # @param [OpenAPIParser::Schemas::Parameter] param_def
  # @param [Hash] raw_params
  # @param [Boolean] explode
  # @return [Object] Deserialized value
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:378
  def deserialize_label_style(param_def, raw_params, explode); end

  # Deserialize matrix style (path parameters)
  # @param [OpenAPIParser::Schemas::Parameter] param_def
  # @param [Hash] raw_params
  # @param [Boolean] explode
  # @return [Object] Deserialized value
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:416
  def deserialize_matrix_style(param_def, raw_params, explode); end

  # Deserialize parameters for a specific location (query, path, header)
  # @param [Hash] raw_params Raw parameters
  # @param [String] location Parameter location ('query', 'path', 'header')
  # @return [Hash] Deserialized parameters
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:46
  def deserialize_params_by_location(raw_params, location); end

  # Deserialize pipe-delimited style (query parameters, arrays only)
  # @param [OpenAPIParser::Schemas::Parameter] param_def
  # @param [Hash] raw_params
  # @param [Boolean] explode
  # @return [Array, nil] Deserialized array
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:527
  def deserialize_pipe_delimited(param_def, raw_params, explode); end

  # Deserialize simple style (path and header parameters)
  # @param [OpenAPIParser::Schemas::Parameter] param_def
  # @param [Hash] raw_params
  # @param [Boolean] explode
  # @return [Object] Deserialized value
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:347
  def deserialize_simple_style(param_def, raw_params, explode); end

  # Deserialize space-delimited style (query parameters, arrays only)
  # @param [OpenAPIParser::Schemas::Parameter] param_def
  # @param [Hash] raw_params
  # @param [Boolean] explode
  # @return [Array, nil] Deserialized array
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:513
  def deserialize_space_delimited(param_def, raw_params, explode); end

  # Extract and deserialize a single parameter
  # @param [OpenAPIParser::Schemas::Parameter] param_def Parameter definition
  # @param [Hash] raw_params Raw parameters
  # @return [Object] Deserialized value
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:173
  def extract_and_deserialize(param_def, raw_params); end

  # Extract matrix-style array (explode=false)
  # @param [String] value Matrix-style string
  # @param [String] param_name Parameter name
  # @return [Array] Extracted array
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:452
  def extract_matrix_array_compact(value, param_name); end

  # Extract matrix-style object (explode=false)
  # @param [String] value Matrix-style string
  # @param [String] param_name Parameter name
  # @return [Hash] Extracted object
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:484
  def extract_matrix_object_compact(value, param_name); end

  # Extract matrix-style object (explode=true)
  # @param [String] value Matrix-style string
  # @param [String] param_name Parameter name
  # @return [Hash] Extracted object
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:466
  def extract_matrix_object_exploded(value, param_name); end

  # Extract matrix-style primitive value
  # @param [String] value Matrix-style string
  # @param [String] param_name Parameter name
  # @return [String] Extracted value
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:498
  def extract_matrix_primitive(value, param_name); end

  # @param [Hash] result
  # @param [String] prefix
  # @param [Object] value
  # @return [void]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:158
  def flatten_nested_query_param(result, prefix, value); end

  # Normalize Rack-style nested query hashes into bracket notation when the
  # schema expects bracket-named params or deepObject query params.
  # Example: { "filter" => { "slug" => "/test" } } => { "filter[slug]" => "/test" }
  # @param [Hash] raw_params
  # @param [String] location
  # @param [Array<OpenAPIParser::Schemas::Parameter>] params_for_location
  # @return [Hash]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:117
  def normalize_raw_params(raw_params, location, params_for_location); end

  # Parse comma-separated object (form explode=false)
  # Example: "role,admin,status,active" → { "role" => "admin", "status" => "active" }
  # @param [String] value Comma-separated string
  # @return [Hash] Parsed object
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:308
  def parse_comma_separated_object(value); end

  # Parse key-value pairs with custom delimiters
  # @param [String] value String containing key-value pairs
  # @param [String] pair_delimiter Delimiter between pairs
  # @param [String] kv_delimiter Delimiter between key and value
  # @return [Hash] Parsed object
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:541
  def parse_key_value_pairs(value, pair_delimiter, kv_delimiter); end

  # @param [Array<OpenAPIParser::Schemas::Parameter>] params_for_location
  # @return [Boolean]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:137
  def requires_query_param_flattening?(params_for_location); end

  # @param [String, Symbol] key
  # @param [Object] value
  # @param [Array<OpenAPIParser::Schemas::Parameter>] params_for_location
  # @return [Boolean]
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/parameter_deserializer.rb:145
  def should_flatten_query_param?(key, value, params_for_location); end
end

# pkg:gem/committee#lib/committee/schema_validator/open_api_3/request_validator.rb:6
class Committee::SchemaValidator::OpenAPI3::RequestValidator
  # @param [SchemaValidator::OpenAPI3::OperationWrapper] operation_object
  # @param [Committee::SchemaValidator::Option] validator_option
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/request_validator.rb:9
  def initialize(operation_object, validator_option:); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/request_validator.rb:14
  def call(request, path_params, query_params, body_params, headers); end

  private

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/request_validator.rb:23
  def check_content_type(request, content_type); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/request_validator.rb:42
  def empty_request?(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/request_validator.rb:38
  def valid_content_types; end
end

# pkg:gem/committee#lib/committee/schema_validator/open_api_3/response_validator.rb:6
class Committee::SchemaValidator::OpenAPI3::ResponseValidator
  # @param [Committee::SchemaValidator::Options] validator_option
  # @param [Committee::SchemaValidator::OpenAPI3::OperationWrapper] operation_wrapper
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/response_validator.rb:11
  def initialize(operation_wrapper, validator_option); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/response_validator.rb:19
  def call(status, headers, response_data, strict); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/response_validator.rb:27
  def validate?(status); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/response_validator.rb:7
  def validate_success_only; end

  private

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/response_validator.rb:42
  def check_header; end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/response_validator.rb:42
  def operation_wrapper; end
end

# pkg:gem/committee#lib/committee/schema_validator/open_api_3/router.rb:6
class Committee::SchemaValidator::OpenAPI3::Router
  # @param [Committee::SchemaValidator::Option] validator_option
  #
  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/router.rb:8
  def initialize(schema, validator_option); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/router.rb:20
  def build_schema_validator(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/router.rb:14
  def includes_request?(request); end

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/router.rb:24
  def operation_object(request); end

  private

  # pkg:gem/committee#lib/committee/schema_validator/open_api_3/router.rb:37
  def prefix_request?(request); end
end

# pkg:gem/committee#lib/committee/schema_validator/option.rb:5
class Committee::SchemaValidator::Option
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:12
  def initialize(options, schema, schema_type); end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def allow_blank_structures; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def allow_empty_date_and_datetime; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def allow_form_params; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def allow_get_body; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def allow_non_get_query_params; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def allow_query_params; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def check_content_type; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def check_header; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def coerce_date_times; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def coerce_form_params; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def coerce_path_params; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def coerce_query_params; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def coerce_recursive; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def coerce_response_values; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def deserialize_parameters; end

  # Non-boolean options:
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:10
  def headers_key; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def optimistic_json; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def parameter_overwrite_by_rails_rule; end

  # Non-boolean options:
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:10
  def params_key; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def parse_response_by_content_type; end

  # Non-boolean options:
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:10
  def path_hash_key; end

  # Non-boolean options:
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:10
  def prefix; end

  # Non-boolean options:
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:10
  def query_hash_key; end

  # Non-boolean options:
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:10
  def request_body_hash_key; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def strict_query_params; end

  # Boolean Options
  #
  # pkg:gem/committee#lib/committee/schema_validator/option.rb:7
  def validate_success_only; end
end

# pkg:gem/committee#lib/committee/test/except_parameter.rb:4
module Committee::Test; end

# Handles temporary parameter exclusion during schema validation.
# Allows testing error responses without validation failures for intentionally missing parameters.
#
# pkg:gem/committee#lib/committee/test/except_parameter.rb:7
class Committee::Test::ExceptParameter
  # @param [Rack::Request] request The request object
  # @param [Hash] committee_options Committee options hash
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:12
  def initialize(request, committee_options); end

  # Apply dummy values to excepted parameters
  # @param [Hash] except Hash of parameter types to parameter names
  #   (e.g., { headers: ['authorization'], query: ['page'] })
  # @return [void]
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:22
  def apply(except); end

  # Restore original parameter values
  # @return [void]
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:31
  def restore; end

  private

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:37
  def handler_for(param_type); end
end

# Base handler for parameters stored in hash-like structures.
# Subclasses implement #get_storage and optionally #dummy_value_for.
#
# pkg:gem/committee#lib/committee/test/except_parameter.rb:109
class Committee::Test::ExceptParameter::BaseHashParameterHandler
  include ::Committee::Test::ExceptParameter::StringDummyLookup

  # @param [Rack::Request] request The request object
  # @param [Hash] committee_options Committee options hash
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:114
  def initialize(request, committee_options); end

  # Apply dummy values to parameters
  # @param [Array<String, Symbol>] param_names Parameter names to except
  # @return [void]
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:123
  def apply(param_names); end

  # Restore original parameter values
  # @return [void]
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:136
  def restore; end

  private

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:153
  def dummy_value_for(key); end

  # Override in subclasses to specify the storage location
  # @return [Hash, nil]
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:149
  def get_storage; end
end

# Handler for request body parameters
#
# Supports three content types:
# - application/json (and variants): replaces rack.input stream so that
#   request_unpack re-parses the modified body during validation.
# - application/x-www-form-urlencoded / multipart/form-data: pre-populates
#   rack.request.form_hash, which Rack returns directly from request.POST
#   without re-parsing the raw body.
# - Other content types (e.g. binary): no-op, as RequestUnpacker does not
#   extract named parameters from them.
#
# pkg:gem/committee#lib/committee/test/except_parameter.rb:227
class Committee::Test::ExceptParameter::BodyHandler
  include ::Committee::Test::ExceptParameter::StringDummyLookup

  # @param [Rack::Request] request The request object
  # @param [Hash] committee_options Committee options hash
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:232
  def initialize(request, committee_options); end

  # Apply dummy values to body parameters based on content type.
  # @param [Array<String, Symbol>] param_names Body parameter names to except
  # @return [void]
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:242
  def apply(param_names); end

  # Restore original body content
  # @return [void]
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:253
  def restore; end

  private

  # --- Form body handling ---
  #
  # Calls request.POST to trigger Rack's form parsing (populating
  # rack.request.form_hash from rack.input), then injects dummy values
  # for missing params into the live hash. In Rack 3.x, request.POST
  # returns rack.request.form_hash directly on subsequent calls, so the
  # injected values are visible during validation.
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:313
  def apply_form(param_names); end

  # --- JSON body handling ---
  #
  # Replaces rack.input with a modified JSON body. Also clears any stale
  # rack.request.form_hash / rack.request.form_pairs caches so that Rack
  # does not return outdated form data if POST is called after the swap.
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:276
  def apply_json(param_names); end

  # --- Dummy value helpers ---
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:340
  def body_hash_key; end

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:399
  def body_param_schema(key); end

  # Returns a native-typed dummy value for JSON bodies.
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:364
  def dummy_value_for(key); end

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:265
  def form_content_type?; end

  # Returns a string-encoded dummy value for form bodies.
  # Form data is always transmitted as strings; openapi_parser's coerce_value
  # handles conversion to the declared type during validation.
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:384
  def form_dummy_for(key); end

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:260
  def json_content_type?; end

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:353
  def parse_body(body_str); end

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:344
  def read_body; end

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:359
  def replace_body(body_str); end

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:329
  def restore_form; end

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:298
  def restore_json; end
end

# pkg:gem/committee#lib/committee/test/except_parameter.rb:8
Committee::Test::ExceptParameter::FORMAT_DUMMIES = T.let(T.unsafe(nil), Hash)

# Handler for request headers
#
# pkg:gem/committee#lib/committee/test/except_parameter.rb:159
class Committee::Test::ExceptParameter::HeaderHandler
  include ::Committee::Test::ExceptParameter::StringDummyLookup

  # @param [Rack::Request] request The request object
  # @param [Hash] committee_options Committee options hash
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:169
  def initialize(request, committee_options); end

  # Apply dummy values to header parameters
  # @param [Array<String, Symbol>] param_names Header names to except
  # @return [void]
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:178
  def apply(param_names); end

  # Restore original header values
  # @return [void]
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:188
  def restore; end

  private

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:196
  def rack_header_key(name); end
end

# In Rack/CGI, Content-Type and Content-Length are stored without the
# HTTP_ prefix. All other headers use the HTTP_ prefix convention.
#
# pkg:gem/committee#lib/committee/test/except_parameter.rb:164
Committee::Test::ExceptParameter::HeaderHandler::SPECIAL_RACK_HEADERS = T.let(T.unsafe(nil), Hash)

# Handler for query parameters
#
# pkg:gem/committee#lib/committee/test/except_parameter.rb:202
class Committee::Test::ExceptParameter::QueryHandler < ::Committee::Test::ExceptParameter::BaseHashParameterHandler
  private

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:212
  def dummy_value_for(key); end

  # pkg:gem/committee#lib/committee/test/except_parameter.rb:205
  def get_storage; end
end

# Shared helpers for looking up OpenAPI3 parameter schemas and generating
# type/format/enum-aware dummy values encoded as HTTP strings.
#
# Included by BaseHashParameterHandler, HeaderHandler, and BodyHandler.
#
# pkg:gem/committee#lib/committee/test/except_parameter.rb:49
module Committee::Test::ExceptParameter::StringDummyLookup
  private

  # Find the OpenAPI3 schema object for a parameter by name and location.
  # Returns nil for non-OpenAPI3 schemas or any lookup failure.
  #
  # Searches both operation-level and path item-level parameters (OpenAPI 3 allows
  # parameters to be declared on the path item and shared across operations).
  # Operation-level parameters take precedence per the OpenAPI spec.
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:72
  def find_parameter_schema(key, location); end

  # Resolve the OpenAPI3 operation object for the current request.
  # Returns nil for non-OpenAPI3 schemas or any lookup failure.
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:54
  def resolve_operation; end

  # Return a type-appropriate dummy value encoded as a String (or Array of strings
  # for array-typed query/path params). The value must be coerceable to the
  # expected schema type by openapi_parser's coerce_value option.
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:88
  def string_dummy_for_schema(key, param_schema); end

  # Return a string that satisfies common OpenAPI3 string format constraints.
  #
  # pkg:gem/committee#lib/committee/test/except_parameter.rb:102
  def string_format_dummy(key, format); end
end

# pkg:gem/committee#lib/committee/test/methods.rb:7
module Committee::Test::Methods
  # pkg:gem/committee#lib/committee/test/methods.rb:13
  def assert_request_schema_confirm(except: T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/test/methods.rb:30
  def assert_response_schema_confirm(expected_status = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/test/methods.rb:8
  def assert_schema_conform(expected_status = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/test/methods.rb:55
  def committee_options; end

  # pkg:gem/committee#lib/committee/test/methods.rb:91
  def old_behavior; end

  # pkg:gem/committee#lib/committee/test/methods.rb:59
  def request_object; end

  # pkg:gem/committee#lib/committee/test/methods.rb:63
  def response_data; end

  # pkg:gem/committee#lib/committee/test/methods.rb:75
  def router; end

  # pkg:gem/committee#lib/committee/test/methods.rb:71
  def schema; end

  # pkg:gem/committee#lib/committee/test/methods.rb:83
  def schema_coverage; end

  # pkg:gem/committee#lib/committee/test/methods.rb:79
  def schema_validator; end

  # pkg:gem/committee#lib/committee/test/methods.rb:67
  def validate_response?(status); end

  private

  # assert_*_schema_confirm signal failure by raising, not via `assert`,
  # so Minitest would report "Test is missing assertions" on success.
  # Bump the counter explicitly; no-op outside Minitest (e.g. RSpec).
  #
  # pkg:gem/committee#lib/committee/test/methods.rb:100
  def increment_assertion_count; end

  # Temporarily adds dummy values for excepted parameters during validation
  # @see ExceptParameter
  #
  # pkg:gem/committee#lib/committee/test/methods.rb:106
  def with_except_params(except); end
end

# pkg:gem/committee#lib/committee/test/schema_coverage.rb:5
class Committee::Test::SchemaCoverage
  # pkg:gem/committee#lib/committee/test/schema_coverage.rb:41
  def initialize(schema); end

  # pkg:gem/committee#lib/committee/test/schema_coverage.rb:58
  def report; end

  # pkg:gem/committee#lib/committee/test/schema_coverage.rb:90
  def report_flatten; end

  # pkg:gem/committee#lib/committee/test/schema_coverage.rb:6
  def schema; end

  # pkg:gem/committee#lib/committee/test/schema_coverage.rb:48
  def update_response_coverage!(path, method, response_status); end

  class << self
    # pkg:gem/committee#lib/committee/test/schema_coverage.rb:25
    def flatten_report(report); end

    # pkg:gem/committee#lib/committee/test/schema_coverage.rb:9
    def merge_report(first, second); end
  end
end

# pkg:gem/committee#lib/committee/utils.rb:4
module Committee::Utils
  class << self
    # pkg:gem/committee#lib/committee/utils.rb:12
    def deep_copy(from); end

    # Creates a Hash with indifferent access.
    #
    # (Copied from Sinatra)
    #
    # pkg:gem/committee#lib/committee/utils.rb:8
    def indifferent_hash; end
  end
end

# pkg:gem/committee#lib/committee/version.rb:4
Committee::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/committee#lib/committee/validation_error.rb:4
class Committee::ValidationError
  # pkg:gem/committee#lib/committee/validation_error.rb:7
  def initialize(status, id, message, request = T.unsafe(nil)); end

  # pkg:gem/committee#lib/committee/validation_error.rb:14
  def error_body; end

  # pkg:gem/committee#lib/committee/validation_error.rb:5
  def id; end

  # pkg:gem/committee#lib/committee/validation_error.rb:5
  def message; end

  # pkg:gem/committee#lib/committee/validation_error.rb:18
  def render; end

  # pkg:gem/committee#lib/committee/validation_error.rb:5
  def request; end

  # pkg:gem/committee#lib/committee/validation_error.rb:5
  def status; end
end
