// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package exports

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

// documentHead renders the head every HTML file of the archive shares.
//
// The encoding declaration is the first child of head so that it stays well
// within the first 1024 bytes a browser reads when it sniffs an encoding: the
// files are opened from the local file system, where there is no Content-Type
// header to fall back on.
//
// [Ja] documentHead はアーカイブの各 HTML ファイルで共通の head を描画する。
//
// 文字コード宣言は head の最初の子に置き、ブラウザが文字コードを判定するために
// 読む先頭 1024 バイトに余裕をもって収まるようにする。これらのファイルはローカル
// ファイルシステムから開かれ、頼れる Content-Type ヘッダーが無いため。
func documentHead(data DocumentData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta name=\"color-scheme\" content=\"light dark\"><meta name=\"mewst-export-format\" content=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(FormatVersion)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/exports/document.templ`, Line: 30, Col: 58}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/exports/document.templ`, Line: 31, Col: 21}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</title><style>\n\t\t\t:root { color-scheme: light dark; }\n\t\t\tbody {\n\t\t\t\tmargin: 0;\n\t\t\t\tpadding: 1.5rem 1rem 3rem;\n\t\t\t\tfont-family: system-ui, -apple-system, \"Hiragino Sans\", \"Noto Sans JP\", sans-serif;\n\t\t\t\tline-height: 1.8;\n\t\t\t\tcolor: #1c1c1e;\n\t\t\t\tbackground-color: #ffffff;\n\t\t\t\toverflow-wrap: anywhere;\n\t\t\t}\n\t\t\tmain { margin: 0 auto; max-width: 40rem; }\n\t\t\th1 { margin: 0 0 1rem; font-size: 1.5rem; line-height: 1.4; }\n\t\t\tul { margin: 1.5rem 0 0; padding: 0; list-style: none; }\n\t\t\tli {\n\t\t\t\tdisplay: flex;\n\t\t\t\tflex-wrap: wrap;\n\t\t\t\tgap: 0 1rem;\n\t\t\t\talign-items: baseline;\n\t\t\t\tjustify-content: space-between;\n\t\t\t\tborder-top: 1px solid #d9d9de;\n\t\t\t}\n\t\t\tli a { display: inline-block; padding: 0.75rem 0; }\n\t\t\ta { color: #0b57d0; }\n\t\t\tarticle { padding: 1rem 0; border-top: 1px solid #d9d9de; }\n\t\t\t.dt-published { display: block; }\n\t\t\t.e-content { margin: 0.25rem 0 0; white-space: pre-wrap; }\n\t\t\t.post-count, .dt-published { color: #4c4c51; font-size: 0.875rem; }\n\t\t\t@media (prefers-color-scheme: dark) {\n\t\t\t\tbody { color: #f2f2f7; background-color: #1c1c1e; }\n\t\t\t\tli, article { border-top-color: #48484a; }\n\t\t\t\ta { color: #8ab4f8; }\n\t\t\t\t.post-count, .dt-published { color: #b0b0b8; }\n\t\t\t}\n\t\t</style></head>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
