name: Formatter

on:
  push:
    paths:
      - "**.js"
      - "**.ts"
      - "**.tsx"
      - "**.css"
      - "**.json"
      - "**.yaml"
      - "**.yml"
      - "**.md"
      - "**.toml"

jobs:
  oxfmt:
    name: Oxfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install
      - run: pnpm fmt:check
