# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Google::Cloud::PubSub::V1::ValidateMessageResponse`.
# Please instead update this file by running `bin/tapioca dsl Google::Cloud::PubSub::V1::ValidateMessageResponse`.

class Google::Cloud::PubSub::V1::ValidateMessageResponse
  sig { void }
  def initialize; end
end
